# Site settings
title: John Arevalo
email: johnarevalo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    John Arevalo personal page. PhD Student at the Universidad Nacional de 
    Colombia
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://johnarevalo.github.io" # the base hostname & protocol for your site
twitter_username: johnarevalo
github_username:  johnarevalo

# Build settings
markdown: kramdown
